# 登录页面
LeJiaLoginPage:
  url: http://school.leyunshe.com.cn/npage/login.html
  用户名输入框: name loginNo
  密码输入框: id password
  登录按钮: xpath //button[text()="登录"][1] 
  

# 登录完成的主页面
LeJiaMainPage:

  # 主页面iframe
  mainFrame: tagname iframe[1]

  loginNameText: id loginNameText 
  
  # 菜单相关
  currentMenuNodelLvOne: xpath '//*[@id="menu"]/li[@class="layui-nav-item layui-nav-itemed"]/a'
  menuNodeLvOne: xpath '//*[@id="menu"]//li/a[contains(text(),"{}")]'
  menuNodeLvTwo: xpath '//*[@id="menu"]//dl/dd/a[contains(@data-title,"{}")]'
  
  
  # 模块搜索相关
  search_keywords: name keywords mainFrame
  # 确认搜索按钮
  search_button: id queryButton mainFrame
  # 搜索重置按钮
  search_reset_button: id queryResetButton mainFrame
  # 表格无数据警告
  table_no_data_tip: classname layui-none mainFrame
  # 操作栏按钮
  table_op_bar: xpath //tbody[1]/tr[{}]/td[last()]//a[text()="{}"] mainFrame
  
  # layer弹出层相关
  layui_confirm_dialog_inner: xpath '//div[@class="layui-layer layui-layer-dialog"]//a[text()="{}"]' mainFrame
  layui_confirm_dialog_outer: xpath '//div[@class="layui-layer layui-layer-dialog"]//a[text()="{}"]'
  
  # 报名受理
  addNewButton: id layerWindow mainFrame  # 新增按钮
  exportButton: id export mainFrame # 导出按钮
  
  # 报名受理表单
  addFormFrame: tagname iframe[2]
  
  addFormComponent_stuName: name stuName addFormFrame
 
  
  